### ISSUE TITLE
device change will result in error in trainning.

### ISSUE THREAD

**Issue by songhat** [notmahi/dobb-e#13]
when i change cpu to gpu in the finetune_task_data.yaml :
```
train:
  _target_: dataloaders.decord_dataset.DecordDataset
  config:
    _target_: dataloaders.utils.DataLoaderConfig
    dataset_root: ${env_vars.finetune_task_data_root}
    trajectory_roots:
      _target_: dataloaders.utils.load_trajectory_roots
      trajectory_root_path: ${dataset.train.config.dataset_root}/r3d_files.txt
      original_root: ${env_vars.finetune_task_data_original_root}
      new_root: ${dataset.train.config.dataset_root}
    include_tasks: 
      - ${include_task}
    exclude_homes: []
    include_envs: 
      - ${include_env}
    sequence_length: 1
    trajectory_subsample_fraction: 1.0
    control_timeskip: 7
    fps_subsample: 1
    relative_gripper: False
    use_depth: ${use_depth}
    binarize_gripper: false
    binarize_gripper_threshold: 0.8
    binarize_gripper_upper_value: 1.0
    binarize_gripper_lower_value: 0.35
  max_videoreaders_in_memory: 128
  shuffle_mode: RANDOM_ORDER
  device: gpu #here


test:
  _target_: dataloaders.decord_dataset.DecordDataset
  config:
    _target_: dataloaders.utils.DataLoaderConfig
    dataset_root: ${env_vars.finetune_task_data_root}
    trajectory_roots:
      _target_: dataloaders.utils.load_trajectory_roots
      trajectory_root_path: ${dataset.test.config.dataset_root}/r3d_files.txt
      original_root: ${env_vars.finetune_task_data_original_root}
      new_root: ${dataset.test.config.dataset_root}
    include_tasks: 
      - ${include_task}
    exclude_homes: []
    include_envs: 
      - ${include_env} 
      # - ${include_env}_val
    sequence_length: ${dataset.train.config.sequence_length}
    control_timeskip: ${dataset.train.config.control_timeskip}
    fps_subsample: ${dataset.train.config.fps_subsample}
    relative_gripper: ${dataset.train.config.relative_gripper}
    use_depth: ${use_depth}
    binarize_gripper: ${dataset.train.config.binarize_gripper}
    binarize_gripper_threshold: ${dataset.train.config.binarize_gripper_threshold}
    binarize_gripper_upper_value: ${dataset.train.config.binarize_gripper_upper_value}
    binarize_gripper_lower_value: ${dataset.train.config.binarize_gripper_lower_value}
  max_videoreaders_in_memory: 128
  shuffle_mode: SEQUENTIAL
  device: gpu #here
```
and I get error in traning. This code runs normally on the CPU.

```
Traceback (most recent call last):
  File "/home1/rhs/code_workspace/dobb-e/imitation-in-homes/train.py", line 411, in main
    workspace.run()
  File "/home1/rhs/code_workspace/dobb-e/imitation-in-homes/train.py", line 190, in run
    self._train_epoch()
  File "/home1/rhs/code_workspace/dobb-e/imitation-in-homes/train.py", line 218, in _train_epoch
    for batch in iterator:
  File "/home1/rhs/.conda/envs/home_robot/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home1/rhs/.conda/envs/home_robot/lib/python3.9/site-packages/accelerate/data_loader.py", line 552, in __iter__
    current_batch = next(dataloader_iter)
  File "/home1/rhs/.conda/envs/home_robot/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/home1/rhs/.conda/envs/home_robot/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
  File "/home1/rhs/.conda/envs/home_robot/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/home1/rhs/.conda/envs/home_robot/lib/python3.9/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
decord._ffi.base.DECORDError: Caught DECORDError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home1/rhs/.conda/envs/home_robot/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home1/rhs/.conda/envs/home_robot/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home1/rhs/.conda/envs/home_robot/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home1/rhs/code_workspace/dobb-e/imitation-in-homes/dataloaders/decord_dataset.py", line 230, in __getitem__
    frames = self._get_video_frames(trajectory_slice)
  File "/home1/rhs/code_workspace/dobb-e/imitation-in-homes/dataloaders/decord_dataset.py", line 247, in _get_video_frames
    videoreader = self._get_video_reader(video_index)
  File "/home1/rhs/code_workspace/dobb-e/imitation-in-homes/dataloaders/decord_dataset.py", line 295, in _get_video_reader
    self._video_reader_cache[index] = decord.VideoReader(
  File "/home1/rhs/.local/lib/python3.9/site-packages/decord-0.6.0-py3.9-linux-x86_64.egg/decord/video_reader.py", line 54, in __init__
    self._handle = _CAPI_VideoReaderGetVideoReader(
  File "/home1/rhs/.local/lib/python3.9/site-packages/decord-0.6.0-py3.9-linux-x86_64.egg/decord/_ffi/_ctypes/function.py", line 173, in __call__
    check_call(_LIB.DECORDFuncCall(
  File "/home1/rhs/.local/lib/python3.9/site-packages/decord-0.6.0-py3.9-linux-x86_64.egg/decord/_ffi/base.py", line 78, in check_call
    raise DECORDError(err_str)
decord._ffi.base.DECORDError: [17:06:39] /home1/rhs/code_workspace/dobb-e/thirdpkg/decord/src/video/nvcodec/cuda_stream.cc:20: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: initialization error at line: 20 in file: /home1/rhs/code_workspace/dobb-e/thirdpkg/decord/src/video/nvcodec/cuda_stream.cc
```

**Comment by notmahi** [comment]
Note that here, the `device` variable is for [decord](https://github.com/dmlc/decord) and not for pytorch. As a result,

1. You need to install gpu-supported decord (https://github.com/dmlc/decord?tab=readme-ov-file#install-from-source) to use it in the first place, and
2. We don't use gpu decoding anyway since in our experiments it is faster to decode on CPU.

We recommend keeping this variable to `cpu`.
